# Permalinks
permalink:        pretty

# Setup
url:              http://stackforyourself.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

# The tags listed as entries in the sidebar
sidebar_tags:     [all, blog]
all_tags:         [general, shell, algorithms, back-end, databases, ruby, rails, ruby-frameworks, front-end, javascript, mobile, working]

# Fallback image and color if not overwritten for tag or post
color:            '#A85641'

author:
  name:    'Esther'
  twitter: mindpl_ace
  github:  mindplace

  # This photo will be used in the about section
  photo:          http://estherleytush.com/assets/headshot.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Esther, [@mindpl_ace on Twitter](https://www.twitter.com/mindpl_ace) and [@mindplace on Github](https://github.com/mindplace/). I love coding, get excited about web development, and
    love sharing what I know with others.

    I'm [elsewhere on the internet](http://estherleytush.com/), and I would love to
    [hear from you](http://estherleytush.com/contact/) about your full-stack journey.

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stack For Yourself
description: > # this means to ignore newlines until "baseurl:"
  A collection of resources on web development.

# Build settings
markdown: kramdown
